language: go
go:
  - stable

env:
  global:
    - GO111MODULE=on
    - secure: kt453yYTNmyK11fUcoVYRuh34Fu4JD7s+W8lSZuihJ1c9Mf2mNEuGbk64uonkns9iOAH5mTvvpB6GzcVmQtbrvXFixDjuvEQK9lpGVt6Q0ASf7iqWDe2leVw7N58301OMMk+rDyugK6E4InCWUaMyRQrihZajVBzHrOntifAx+277wlK8D77EBg26qeNaNeFJiuaQ++qyXp/Y273/IF30Y6MsWA25YigEC5xLQBMGDUD5XNuowi/RIMmHLvxb+zy106zh+s333rz7F1inw6nsS+fkSb65rpxZ4MNRqkzH7OCCKZ4nk3c9tWc7hHVaEWcQCNRyIfANqpET4NjRHJrUVQs38t6T+0ky7Pn0hU44J6y1gCtZjtaCio56V/kIGSCtvgVocS+EJ7efJTHerTYb1HB1s0XG78/6udb+dMbKXkuu4pL57/WcXGqH5AhD1U608os387hKJOznJW+ej/cPce61q/0Muv4vJSw0PMwX51MLVGpw05x2lFsDvMLg0vNI3wkvCUBLZ/vr+roxBziKkHBMwFv7Pk08Z/NiLuYF32AGyhr8ftgCIWLn8WFN0qlrnp0k0smkIZVCCW/p2CfxSlbq0DGuV+wECAaYZDIT9L8ZGgE5cUGSEmIaY4zyC7Q6X+7mSNKP0tisbY1m6GDaoKOkJ90F1TncxGu68KL/50=

install:
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - TABLE_NAME_OVERRIDE=TestAlexaWikipediaRequests ginkgo -r --skipPackage=s3,github

branches:
  except:
    - /^wip.*$/
