language: go
go:
  - stable

env:
  global:
    - GO111MODULE=on

install:
  - go get github.com/onsi/ginkgo/ginkgo

script:
  - TABLE_NAME_OVERRIDE=TestAlexaWikipediaRequests ginkgo -r --skipPackage=s3

branches:
  except:
  - /^wip.*$/
